name: HTTP server

on:
    push:
        branches:
            - master

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola 
              run: echo "Hola mundo"
            - name: Instalar socat
              run: sudo apt-get install -y socat
            - name: Mostrar IP
              run: curl ifconfig.me
            - name: Abrir puerto 1234 y escuchar con socat
              run: socat TCP-LISTEN:1234,reuseaddr,fork EXEC:/bin/bash