name: Hola mundo

on:
    push:
        branches:
            - master

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola mundo
              run: echo "Hola mundo"
            - name: Instalar figlet
              run: sudo apt-get install python3
            - name: Levantar servidor
              run: |
                python -m http.server 8000 &
                sleep 120
                pkill -f "python -m http.server 8000"