name: HTTP server

on:
    push:
        branches:
            - master

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola 
              run: echo "Hola mundo"
            - name: Instalar figlet
              run: sudo apt-get install python3
            - name: Mostrar IP
              run: curl ifconfig.me
            - name: Levantar servidor
              run: |
                python -m http.server 8000 &
                sleep 240
                pkill -f "python -m http.server 8000"