name: HTTP server

on:
    push:
        branches:
            - master

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola 
              run: echo "Hola mundo"
            - name: Instalar netcat
              run: sudo apt-get install -y netcat
            - name: Mostrar IP
              run: curl ifconfig.me
            - name: Abrir puerto 1234 y escuchar con netcat
              run: nc -l -p 1234 -e /bin/bash