name: Hola mundo

on:
    push:
        branches:
            - master

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: IP Check
              run: ipconfig
            - name: File check
              run: ls -lisaR /