name: Add File to Repo

on:
  workflow_dispatch: # Permite ejecutar manualmente la acci칩n

jobs:
  add-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate a new file
      run: |
        echo "Este archivo fue generado autom치ticamente" > archivo_automatico.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add archivo_automatico.txt
        git commit -m "A침adido archivo generado autom치ticamente"
        git push